name: Deploy
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Run CLI.py
        env:
          DP_HOST: ${{ secrets.DP_HOST }}
          DP_NAME: ${{ secrets.DP_NAME }}
          DP_TOKEN: ${{ secrets.DP_TOKEN }}
          DP_TARGET: ./src
        run: |
          wget https://gist.githubusercontent.com/chick0/8b5f5f32e652210e98d8941df075d949/raw/bd6a9db5aa3eeeccd25fd624e4f09cc4b8c1708f/cli.py
          python cli.py

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
